# Generated by Django 4.2.5 on 2023-10-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20231004_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
